name: deploy-workflow

on:
    workflow_dispatch:
    workflow_run:
        workflows: [develop, testing, staging, qa, preproduction, production]  # Define los workflows que pueden activarlo
        types:
        - completed

env:
    ENVIRONMENTS: |
        {
        "develop": "testing",
        "testing": "staging",
        "staging": "qa",
        "qa": "preproduction",
        "preproduction": "production",
        "production": "production"
        }

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        environment: ${{ fromJson(env.ENVIRONMENTS)[github.event.workflow.name] }}  # Obtiene el entorno correcto dinámicamente
        uses: saguit03/proyecto24-gb01-usuarios-sgt/.github/workflows/learning-called.yml@actions
        with:
            env-type: ${{ fromJson(env.ENVIRONMENTS)[github.event.workflow.name] }}

    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        environment: ${{ fromJson(env.ENVIRONMENTS)[github.event.workflow.name] }}
        steps:
        - run: echo 'The triggering workflow failed'
        - run: exit 1
