name: develop

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    uses: saguit03/proyecto24-gb01-usuarios-sgt/.github/workflows/learning-called.yml@actions
    with:
      env-type: 'develop'
