on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  CallerMatrix:
    strategy:
      matrix:
        env-type: [develop, testing, production]
    uses: saguit03/proyecto24-gb01-usuarios-sgt/.github/workflows/learning-called.yml@actions
    with:
      env-type: ${{ matrix.env-type }}