name: testing

on:
  workflow_run:
    workflows: [develop]
    types:
      - completed

jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: saguit03/proyecto24-gb01-usuarios-sgt/.github/workflows/learning-called.yml@actions
    with:
      env-type: 'testing'
  on-failure:
    environment: 'testing'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: exit 1